apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: mysql-secret
  data:
    - secretKey: {{ .Values.aws.secretProperty }}
      remoteRef:
        key: {{ .Values.aws.secretName }}
        property: {{ .Values.aws.secretProperty }}